name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
 easy_cron:
   path: ../

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
